stages:
  - build
  - test

# Define the Docker image to be used for the job
image: python:3.8

# Cache dependencies to speed up builds
cache:
  paths:
    - .venv/

# Build stage for Flask WebApp
build:
  stage: build
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r web/requirements.txt
  artifacts:
    paths:
      - .venv/

#Test Stage using PyTest
test:
  stage: test
  dependencies:
    - build
  script:
    - source .venv/bin/activate
    - pytest
